const $ = (selector) => document.querySelector(selector);
let mode = 'login';
const state = { user: null };
function showAuth(){ $('#auth-view').classList.remove('hidden'); $('#chat-view').classList.add('hidden'); $('#logout').classList.add('hidden'); }
function showChat(){ $('#auth-view').classList.add('hidden'); $('#chat-view').classList.remove('hidden'); $('#logout').classList.remove('hidden'); loadHistory(); }
function escapeHtml(value){ const div=document.createElement('div'); div.textContent=value; return div.innerHTML; }
function addMessage(role, content){ const row=document.createElement('div'); row.className=`message ${role}`; row.innerHTML=`${role==='assistant'?'<span class="bot-mark">K</span>':''}<div class="bubble">${escapeHtml(content)}</div>`; $('#messages').append(row); $('#messages').scrollTop=$('#messages').scrollHeight; }
async function api(url, options={}){ const response=await fetch(url,{credentials:'include',headers:{'Content-Type':'application/json',...(options.headers||{})},...options}); const data=await response.json().catch(()=>({})); if(!response.ok) throw new Error(data.error||'Une erreur est survenue.'); return data; }
async function loadHistory(){ try{ const data=await api('/api/chat/history'); if(data.messages.length){ $('#messages').innerHTML=''; data.messages.forEach(m=>addMessage(m.role,m.content)); } }catch(e){ showAuth(); } }
$('.tabs').addEventListener('click',e=>{ const button=e.target.closest('.tab'); if(!button)return; mode=button.dataset.mode; document.querySelectorAll('.tab').forEach(tab=>tab.classList.toggle('active',tab===button)); $('#auth-submit').textContent=mode==='login'?'Entrer dans KrakenAI':'Créer mon compte'; $('#password').autocomplete=mode==='login'?'current-password':'new-password'; $('#auth-error').textContent=''; });
$('#auth-form').addEventListener('submit',async e=>{ e.preventDefault(); const submit=$('#auth-form button[type=submit]'); submit.disabled=true; $('#auth-error').textContent=''; try{ const data=await api(`/api/auth/${mode}`,{method:'POST',body:JSON.stringify({email:$('#email').value,password:$('#password').value})}); state.user=data.user; showChat(); }catch(error){ $('#auth-error').textContent=error.message; }finally{ submit.disabled=false; } });
$('#logout').addEventListener('click',async()=>{ await api('/api/auth/logout',{method:'POST'}).catch(()=>{}); state.user=null; showAuth(); });
$('#clear-chat').addEventListener('click',async()=>{ if(!confirm('Effacer tout l’historique ?'))return; await api('/api/chat/history',{method:'DELETE'}); $('#messages').innerHTML=''; });
$('#messages').addEventListener('click',e=>{ const button=e.target.closest('.suggestions button'); if(button){ $('#message').value=button.textContent; $('#message').focus(); } });
$('#chat-form').addEventListener('submit',async e=>{ e.preventDefault(); const input=$('#message'), button=$('.send'), message=input.value.trim(); if(!message)return; input.value=''; input.style.height='auto'; button.disabled=true; addMessage('user',message); const typing=document.createElement('div'); typing.className='typing'; typing.textContent='KrakenAI réfléchit…'; $('#messages').append(typing); $('#messages').scrollTop=$('#messages').scrollHeight; try{ const data=await api('/api/chat',{method:'POST',body:JSON.stringify({message})}); typing.remove(); addMessage('assistant',data.message.content); }catch(error){ typing.remove(); addMessage('assistant',`Erreur : ${error.message}`); }finally{ button.disabled=false; input.focus(); } });
$('#message').addEventListener('input',e=>{ e.target.style.height='auto'; e.target.style.height=Math.min(e.target.scrollHeight,180)+'px'; });
(async()=>{ try{ const data=await api('/api/auth/me'); state.user=data.user; showChat(); }catch{ showAuth(); }})();
